/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_irefire_mp3_LameWrapper */

#ifndef _Included_com_irefire_mp3_LameWrapper
#define _Included_com_irefire_mp3_LameWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_irefire_mp3_LameWrapper
 * Method:    nativeGetVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_irefire_mp3_LameWrapper_nativeGetVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_irefire_mp3_LameWrapper
 * Method:    nativeInit
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_irefire_mp3_LameWrapper_nativeInit
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_irefire_mp3_LameWrapper
 * Method:    nativePrepare
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_irefire_mp3_LameWrapper_nativePrepare
  (JNIEnv *, jclass);

/*
 * Class:     com_irefire_mp3_LameWrapper
 * Method:    nativeEncodeBuffer
 * Signature: ([S[SI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_irefire_mp3_LameWrapper_nativeEncodeBuffer
  (JNIEnv *, jclass, jshortArray, jshortArray, jint);

/*
 * Class:     com_irefire_mp3_LameWrapper
 * Method:    nativeEncoderBufferInterleaved
 * Signature: ([SI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_irefire_mp3_LameWrapper_nativeEncoderBufferInterleaved
  (JNIEnv *, jclass, jshortArray, jint);

/*
 * Class:     com_irefire_mp3_LameWrapper
 * Method:    nativeEncodeFlush
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_irefire_mp3_LameWrapper_nativeEncodeFlush
  (JNIEnv *, jclass);

/*
 * Class:     com_irefire_mp3_LameWrapper
 * Method:    nativeRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_irefire_mp3_LameWrapper_nativeRelease
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
